openapi: 3.0.4
info:
  title: Scotland Yard API
  version: 1.0.0
  description: API for playing Scotland Yard.

paths:
  /map/stations:
    get:
      summary: Get all stations
      responses:
        "200":
          description: List of stations
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: number
                      description: ID of the station
                    pos_x:
                      type: number
                      description: X coordinate of the station
                    pos_y:
                      type: number
                      description: Y coordinate of the station
                    types:
                      type: array
                      description: Available transportation types at this station
                      items:
                        type: string
                        enum: [taxi, bus, underground]

  /map/connections:
    get:
      summary: Get all connections between stations
      responses:
        "200":
          description: List of connections
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    from:
                      type: number
                      description: ID of the origin station
                    to:
                      type: number
                      description: ID of the destination station
                    mode:
                      type: string
                      enum: [taxi, bus, underground, water]
                      description: Type of connection

  /map/rounds:
    get:
      summary: Get structure of rounds
      responses:
        "200":
          description: List of rounds
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    index:
                      type: number
                      description: Index of the round
                    show_mister_x:
                      type: boolean
                      description: Whether Mister X is shown in this round

  /game/ws:
    get:
      summary: Upgrade to WebSocket
      description: |
        Clients connect to this endpoint using a WebSocket handshake.
      responses:
        "101":
          description: Switching Protocols (WebSocket upgrade)
